attention_resolutions: 32,16,8
class_cond: false
diffusion_steps: 1000
learn_sigma: true
noise_schedule: linear
num_channels: 256
num_head_channels: 64
num_heads: 4
num_res_blocks: 2
resblock_updown: true
use_fp16: false
use_scale_shift_norm: true
classifier_scale: 4.0
lr_kernel_n_std: 2
num_samples: 100
show_progress: true
timestep_respacing: '250'
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_use_fp16: false
classifier_width: 128
classifier_depth: 2
classifier_attention_resolutions: 32,16,8
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
num_heads_upsample: -1
channel_mult: ''
dropout: 0.0
use_checkpoint: false
use_new_attention_order: false
clip_denoised: true
use_ddim: false
image_size: 256
model_path: ./pretrained/places256_300000.pt
name: test_p256_thick
inpa_inj_sched_prev: true
n_jobs: 25
print_estimated_vars: true
inpa_inj_sched_prev_cumnoise: false
schedule_jump_params:
  t_T: 250
  n_sample: 1
  jump_length: 10
  jump_n_sample: 10
data:
  eval:
    lama_p256_thick_n100_test:
      mask_loader: true
      gt_path: /workspace/DropWiper/datasets/RainDrop_resized/test/data
      mask_path: /workspace/DropWiper/datasets/RainDrop_resized/test/mask
      image_size: 256
      class_cond: false
      deterministic: true
      random_crop: false
      random_flip: false
      return_dict: true
      drop_last: false
      batch_size: 8
      return_dataloader: true
      ds_conf:
        name: random_thick_256
      max_len: 100
      paths:
        srs: ./log/test_raindrop_p256/inpainted
        lrs: ./log/test_raindrop_p256/gt_masked
        gts: ./log/test_raindrop_p256/gt
        gt_keep_masks: ./log/test_raindrop_p256/gt_keep_mask